### ISSUE TITLE
Difference in function name between minified and non minified

### ISSUE THREAD

**Issue by terryupton** [sdeering/jquery-quick-pagination#1]
I noticed that the non minified version has a different function name called quickPager where as the minified version has a function called quickPagination.

I like to use the original version as I do my own minification. I thought I should mention this as I spotted it so you can align the two versions.

Thanks.

**Comment by terryupton** [comment]
Just to add I prefer the function name as quickPagination as per the minified version.

**Comment by sdeering** [comment]
@terryupton Thanks mate, I agree with you I prefer quick pagination.

![image](https://cloud.githubusercontent.com/assets/1787454/7601734/bcefd414-f95d-11e4-9eee-6998b598094f.png)
